/**
 * Created by Administrator on 2015/9/11.
 */
app.controller('getParameter',['$http','$scope','$stateParams',function($http,$scope,$stateParams){
    $scope.condition={
        categoryId:$stateParams.categoryId
    }
    $http.get(SETTING.ZergWcApiUrl+"/ProductParameter/Get",{
        params:$scope.condition,
        'withCredentials':true
    }).success(function(data){
        $scope.list=data.List
    })
    $http.get(SETTING.ZergWcApiUrl+"/CommunityProduct/Get?id="+$stateParams.productId,{
        'widthCreadentials':true
    }).success(function(data){
        $scope.product=data;
    })
}])
app.controller('parameterCreateCtr',['$http','$scope','$state',function($http,$scope,$state){
    $scope.model={
        productId:'',
        ParameterId:'',
        ParameterValueId:''
    }
    $http.put(SETTING.ZergWcApiUrl+"/ProductParameter/Put",$scope.model,{
        'withCredentials':true
    }).success(function(data){
        if(data.Status){
            $state.go("app.product.productList");
        }
    })
}])