//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yoopoon.home.ui.home;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.ImageView;
import android.widget.TextView;
import com.yoopoon.home.R.id;
import com.yoopoon.home.R.layout;
import com.yoopoon.home.ui.view.BadgeView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MainTabView_
    extends MainTabView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public MainTabView_(Context context) {
        super(context);
        init_();
    }

    public MainTabView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public MainTabView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static MainTabView build(Context context) {
        MainTabView_ instance = new MainTabView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.main_tab_view, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static MainTabView build(Context context, AttributeSet attrs) {
        MainTabView_ instance = new MainTabView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static MainTabView build(Context context, AttributeSet attrs, int defStyle) {
        MainTabView_ instance = new MainTabView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        badgeView = ((BadgeView) hasViews.findViewById(id.badgeView));
        title = ((TextView) hasViews.findViewById(id.title));
        imageView = ((ImageView) hasViews.findViewById(id.imageView));
    }

}
